openapi: 3.0.0
info:
  title: API v1
  version: '1.0'
  description: blablahome API
servers:
  - url: 'https://blablahome.lazureykis.dev/api'
    description: prod
  - url: 'http://localhost:4000/api'
    description: dev
paths:
  /status:
    get:
      summary: Server Status
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - ok
                      - error
                required:
                  - status
      operationId: get-status
      description: Healthcheck endpoint
      requestBody:
        description: ''
  /users:
    post:
      summary: Users
      operationId: post-users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - ok
                  user:
                    $ref: '#/components/schemas/User'
                required:
                  - status
              examples:
                valid user:
                  value:
                    status: ok
                    user:
                      id: '82317456129'
                      name: Ivan
                      picture_url: 'https://platform-lookaside.fbsbx.com/platform/profilepic/?asid=10221848305782264&height=50&width=50&ext=1588687492&hash=AeSj5OUCPVDTbfM-'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - error
                  error:
                    type: string
                required:
                  - status
                  - error
              examples:
                error:
                  value:
                    status: error
                    error: Some error reason
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                access_token:
                  type: string
            examples:
              example-1: {}
      description: User registration
  /activities:
    post:
      summary: Create new activity
      operationId: post-activities
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Activity'
              examples:
                example-1:
                  value:
                    cover: 'https://storage.googleapis.com/blablahome/uploads/activities/covers/62bed2d2-1ce4-49c0-a068-031d69aa1117/0.jpeg?v=63753130513'
                    days: 7
                    description: Testing
                    id: 62bed2d2-1ce4-49c0-a068-031d69aa1117
                    name: Test
                    user:
                      id: 0ac2009f-584b-4462-906a-4d1028d32e5f
                      name: Pavel Lazureykis
                      picture_url: 'https://platform-lookaside.fbsbx.com/platform/profilepic/?asid=10221848305782264&height=50&width=50&ext=1588687492&hash=AeSj5OUCPVDTbfM-'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  error:
                    type: string
              examples:
                example-1:
                  value:
                    error: unauthorized
                    status: error
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
              examples:
                without a name and description:
                  value:
                    errors:
                      description:
                        - "can't be blank"
                      name:
                        - "can't be blank"
      security:
        - Bearer authorization: []
      description: ''
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                cover:
                  type: string
                days:
                  type: number
                  minimum: 1
                  maximum: 7
              required:
                - name
                - description
                - days
            examples:
              example-1: {}
        description: Use http uploaded file for cover attribute.
    get:
      summary: List activities
      operationId: get-activities
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Activity'
              examples:
                example-1:
                  value:
                    - cover: 'https://storage.googleapis.com/blablahome/uploads/activities/covers/62bed2d2-1ce4-49c0-a068-031d69aa1117/0.jpeg?v=63753130513'
                      days: 7
                      description: Testing
                      id: 62bed2d2-1ce4-49c0-a068-031d69aa1117
                      name: Test
                      user:
                        id: 0ac2009f-584b-4462-906a-4d1028d32e5f
                        name: Pavel Lazureykis
                        picture_url: 'https://platform-lookaside.fbsbx.com/platform/profilepic/?asid=10221848305782264&height=50&width=50&ext=1588687492&hash=AeSj5OUCPVDTbfM-'
      description: ''
    parameters: []
  '/activities/{activity_id}/participations':
    post:
      summary: Participations for activity
      operationId: 'post-activities-:id-participations'
      responses:
        '201':
          description: Created
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                example-1:
                  value:
                    id: c59c229e-3a53-462c-b4e2-2d41c07f59b3
                    progress: 0
                    completed_at: null
                    user:
                      id: 0ac2009f-584b-4462-906a-4d1028d32e5f
                      name: Pavel Lazureykis
                      picture_url: 'https://platform-lookaside.fbsbx.com/platform/profilepic/?asid=10221848305782264&height=50&width=50&ext=1588687492&hash=AeSj5OUCPVDTbfM-'
                    activity:
                      cover: 'https://storage.googleapis.com/blablahome/uploads/activities/covers/62bed2d2-1ce4-49c0-a068-031d69aa1117/0.jpeg?v=63753130513'
                      days: 7
                      description: Testing
                      id: 62bed2d2-1ce4-49c0-a068-031d69aa1117
                      name: Test
      description: Create participation. User joins the activity.
      security:
        - Bearer authorization: []
    parameters:
      - schema:
          type: string
        name: activity_id
        in: path
        required: true
    get:
      summary: List participations by activity id
      operationId: get-activities-activity_id-participations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Participation'
              examples:
                example-1:
                  value:
                    - id: c59c229e-3a53-462c-b4e2-2d41c07f59b3
                      progress: 0
                      completed_at: null
                      user:
                        id: 0ac2009f-584b-4462-906a-4d1028d32e5f
                        name: Pavel Lazureykis
                        picture_url: 'https://platform-lookaside.fbsbx.com/platform/profilepic/?asid=10221848305782264&height=50&width=50&ext=1588687492&hash=AeSj5OUCPVDTbfM-'
                      activity:
                        cover: 'https://storage.googleapis.com/blablahome/uploads/activities/covers/62bed2d2-1ce4-49c0-a068-031d69aa1117/0.jpeg?v=63753130513'
                        days: 7
                        description: Testing
                        id: 62bed2d2-1ce4-49c0-a068-031d69aa1117
                        name: Test
                        user:
                          id: 0ac2009f-584b-4462-906a-4d1028d32e5f
                          name: Pavel Lazureykis
                          picture_url: 'https://platform-lookaside.fbsbx.com/platform/profilepic/?asid=10221848305782264&height=50&width=50&ext=1588687492&hash=AeSj5OUCPVDTbfM-'
      description: ''
  '/users/{user_id}/participations':
    get:
      summary: Participations
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Participation'
              examples:
                example-1:
                  value:
                    - id: c59c229e-3a53-462c-b4e2-2d41c07f59b3
                      progress: 0
                      completed_at: null
                      user:
                        id: 0ac2009f-584b-4462-906a-4d1028d32e5f
                        name: Pavel Lazureykis
                        picture_url: 'https://platform-lookaside.fbsbx.com/platform/profilepic/?asid=10221848305782264&height=50&width=50&ext=1588687492&hash=AeSj5OUCPVDTbfM-'
                      activity:
                        cover: 'https://storage.googleapis.com/blablahome/uploads/activities/covers/62bed2d2-1ce4-49c0-a068-031d69aa1117/0.jpeg?v=63753130513'
                        days: 7
                        description: Testing
                        id: 62bed2d2-1ce4-49c0-a068-031d69aa1117
                        name: Test
                        user:
                          id: 0ac2009f-584b-4462-906a-4d1028d32e5f
                          name: Pavel Lazureykis
                          picture_url: 'https://platform-lookaside.fbsbx.com/platform/profilepic/?asid=10221848305782264&height=50&width=50&ext=1588687492&hash=AeSj5OUCPVDTbfM-'
      operationId: get-participations
      security:
        - Bearer authorization: []
      description: "List currrent user's active participations."
    parameters:
      - schema:
          type: string
        name: user_id
        in: path
        required: true
  '/activities/{activity_id}/checkin':
    parameters:
      - schema:
          type: string
        name: activity_id
        in: path
        required: true
    post:
      summary: Create check-in
      operationId: post-activities-activity_id-checkin
      responses:
        '200':
          description: OK
      security:
        - Bearer authorization: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                photo:
                  type: string
                  description: URL
                participation:
                  $ref: '#/components/schemas/Participation'
              required:
                - photo
                - participation
                - photo
            examples:
              example-1:
                value:
                  likes: 0
                  message: hello
                  participation:
                    id: abe48c10-bb5c-42d4-a31f-f7bc2b5be1e9
                    progress: 0
                    completed_at: null
                    user:
                      id: 0ac2009f-584b-4462-906a-4d1028d32e5f
                      name: Pavel Lazureykis
                      picture_url: 'https://platform-lookaside.fbsbx.com/platform/profilepic/?asid=10221848305782264&height=50&width=50&ext=1588687492&hash=AeSj5OUCPVDTbfM-'
                    activity:
                      completions_count: 0
                      cover: 'https://storage.googleapis.com/blablahome/uploads/activities/covers/31b75050-4308-4084-930f-e55ed78198e1/0.jpeg?v=63753151111'
                      days: 3
                      description: Testing
                      fails_count: 0
                      id: 31b75050-4308-4084-930f-e55ed78198e1
                      name: Test 3
                      participants_count: 1
                      user:
                        id: 0ac2009f-584b-4462-906a-4d1028d32e5f
                        name: Pavel Lazureykis
                        picture_url: 'https://platform-lookaside.fbsbx.com/platform/profilepic/?asid=10221848305782264&height=50&width=50&ext=1588687492&hash=AeSj5OUCPVDTbfM-'
                  photo: 'https://storage.googleapis.com/blablahome/uploads/checkins/photos/e4e004eb-646b-4fd9-96d1-d3f020b4868c/0.jpeg?v=63753151161'
                  progress: 1
        description: ''
  /checkins:
    get:
      summary: Get last check-ins
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Checkin'
              examples:
                example-1:
                  value:
                    - id: b9f45fb3-a1a0-4167-b292-5b0d6e2985fa
                      likes: 0
                      message: hello
                      participation:
                        id: 36f8cd13-92c5-451b-ae8e-292cec76edc8
                        progress: 0
                        completed_at: null
                        user:
                          id: 0ac2009f-584b-4462-906a-4d1028d32e5f
                          name: Pavel Lazureykis
                          joins_count: 1
                          completions_count: 4
                          fails_count: 0
                        activity:
                          completions_count: 0
                          cover: 'https://storage.googleapis.com/blablahome/uploads/activities/covers/62bed2d2-1ce4-49c0-a068-031d69aa1117/0.jpeg?v=63753130513'
                          days: 7
                          description: Testing
                          fails_count: 0
                          id: 62bed2d2-1ce4-49c0-a068-031d69aa1117
                          name: Test
                          participants_count: 2
                          user:
                            id: 0ac2009f-584b-4462-906a-4d1028d32e5f
                            name: Pavel Lazureykis
                            joins_count: 1
                            completions_count: 4
                            fails_count: 0
                      photo: 'https://storage.googleapis.com/blablahome/uploads/checkins/photos/b9f45fb3-a1a0-4167-b292-5b0d6e2985fa/0.jpeg?v=63753146078'
                      progress: 2
                    - id: 85543b1e-defe-406f-b26c-85b69d6ceb0a
                      likes: 0
                      message: hello
                      participation:
                        id: 36f8cd13-92c5-451b-ae8e-292cec76edc8
                        progress: 0
                        completed_at: null
                        user:
                          id: 0ac2009f-584b-4462-906a-4d1028d32e5f
                          name: Pavel Lazureykis
                          joins_count: 1
                          completions_count: 4
                          fails_count: 0
                        activity:
                          completions_count: 0
                          cover: 'https://storage.googleapis.com/blablahome/uploads/activities/covers/62bed2d2-1ce4-49c0-a068-031d69aa1117/0.jpeg?v=63753130513'
                          days: 7
                          description: Testing
                          fails_count: 0
                          id: 62bed2d2-1ce4-49c0-a068-031d69aa1117
                          name: Test
                          participants_count: 2
                          user:
                            id: 0ac2009f-584b-4462-906a-4d1028d32e5f
                            name: Pavel Lazureykis
                            joins_count: 1
                            completions_count: 4
                            fails_count: 0
                      photo: 'https://storage.googleapis.com/blablahome/uploads/checkins/photos/85543b1e-defe-406f-b26c-85b69d6ceb0a/0.jpeg?v=63753145943'
                      progress: 1
      operationId: get-checkins
      description: ''
components:
  schemas:
    User:
      title: User
      type: object
      description: Authorized user
      x-examples:
        example-1: {}
      properties:
        id:
          type: string
        name:
          type: string
        joins_count:
          type: integer
        completions_count:
          type: integer
        fails_count:
          type: integer
        picture_url:
          type: string
    Activity:
      title: Activity
      type: object
      x-examples:
        example:
          cover: 'https://storage.googleapis.com/blablahome/uploads/activities/covers/62bed2d2-1ce4-49c0-a068-031d69aa1117/0.jpeg?v=63753130513'
          days: 7
          description: Testing
          id: 62bed2d2-1ce4-49c0-a068-031d69aa1117
          name: Test
          user:
            id: 0ac2009f-584b-4462-906a-4d1028d32e5f
            name: Pavel Lazureykis
      description: 'Type of activity - 100 pushups, read a book, etc.'
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        cover:
          type: string
        days:
          type: integer
          format: int32
          example: '2'
          minimum: 1
          maximum: 7
        user:
          $ref: '#/components/schemas/User'
        participants_count:
          type: integer
          minimum: 0
        completions_count:
          type: integer
          minimum: 0
        fails_count:
          type: integer
          minimum: 0
    Participation:
      title: Participation
      type: object
      description: "User's participation in Activity"
      properties:
        id:
          type: string
        progress:
          type: integer
          example: '2'
          minimum: 0
          maximum: 7
        completed_at:
          type:
            - string
            - 'null'
          format: date-time
          example: '2020-04-03T11:23:15'
        user:
          $ref: '#/components/schemas/User'
        activity:
          $ref: '#/components/schemas/Activity'
      required:
        - id
        - progress
        - completed_at
        - user
        - activity
      x-examples:
        example-1:
          id: d77f0583-82f0-4565-9e99-70864d3cb9ab
          progress: 0
          completed_at: '2020-04-03T11:23:15'
          user:
            id: 0ac2009f-584b-4462-906a-4d1028d32e5f
            name: Pavel Lazureykis
          activity:
            cover: 'https://storage.googleapis.com/blablahome/uploads/activities/covers/62bed2d2-1ce4-49c0-a068-031d69aa1117/0.jpeg?v=63753130513'
            days: 7
            description: Testing
            id: 62bed2d2-1ce4-49c0-a068-031d69aa1117
            name: Test
    Checkin:
      title: Checkin
      type: object
      description: Check-in object
      properties:
        id:
          type: string
        message:
          type: string
        photo:
          type: string
          description: URL
        progress:
          type: integer
          minimum: 0
          maximum: 7
        likes:
          type: integer
          minimum: 0
        participation:
          $ref: '#/components/schemas/Participation'
      required:
        - id
        - photo
        - progress
        - likes
        - participation
  securitySchemes:
    Bearer authorization:
      name: Authorization
      type: apiKey
      in: header
      description: Used for protected endpoints
